name: Incubaid Staging
on:
  push:
    branch: [ development ]


jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: pushing latest change on www2.incubaid.com
      uses: appleboy/ssh-action@master
      with:
        host: www2.incubaid.com
        username: ${{ secrets.TF_USER }}
        key: ${{ secrets.TF_SECRET }}
        port: ${{ secrets.TF_PORT }}
        script: |
          cd websites/www2/www_incubaid_zola/
          git log -1
          git restore .
          git pull
          bash build.sh