name: Incubaid Zola
on:
  push:
    branch: [main]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: pushing latest change on incubaid production
        uses: appleboy/ssh-action@master
        with:
          host: incubaid.com
          username: ${{ secrets.TF_USER }}
          key: ${{ secrets.TF_SECRET }}
          port: ${{ secrets.TF_PORT }}
          script: |
            cd websites/www_incubaid_zola
            git log -1
            git restore .
            git pull
            bash build.sh
