name: Incubaid Production
on:
  push:
    branches: 
      - main


jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: pushing latest change on www.incubaid.com
      uses: appleboy/ssh-action@master
      with:
        host: www.incubaid.com
        username: ${{ secrets.TF_USER }}
        key: ${{ secrets.TF_SECRET }}
        port: ${{ secrets.TF_PORT }}
        script: |
          cd websites/www_incubaid_zola/
          git log -1
          git fetch
          git reset --hard origin/main
          sed -i "s/https:\/\/www2.incubaid.com/https:\/\/www.incubaid.com/g" config.toml
          bash build.sh
